import { Link } from "wouter";

function LegalShell({ title, children }: { title: string; children: React.ReactNode }) {
  return <main className="min-h-screen bg-slate-50 px-5 py-12 text-slate-900 sm:px-8"><article className="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-7 shadow-sm sm:p-10"><Link href="/" className="text-sm font-medium text-sky-700 underline underline-offset-4">Small Stories Hebrew</Link><h1 className="mt-5 text-3xl font-bold tracking-tight">{title}</h1><p className="mt-2 text-sm text-slate-500">Last updated: 26 August 2026</p><div className="mt-8 space-y-6 leading-7 text-slate-700">{children}</div></article></main>;
}

export function PrivacyPolicy() {
  return <LegalShell title="Privacy Policy"><p>Small Stories Hebrew is an internal creator tool used by the channel owner to prepare and manage original, child-directed Hebrew stories on YouTube. It is not a public consumer application.</p><section><h2 className="text-xl font-semibold text-slate-900">Information handled</h2><p>The service handles the Google OAuth authorization needed for the owner’s channel, encrypted refresh-token material, video metadata, private-upload status, and authorized YouTube performance data. It does not collect viewer profiles, comments, passwords, or Google verification codes.</p></section><section><h2 className="text-xl font-semibold text-slate-900">How information is used</h2><p>Authorized YouTube API data is used only to upload owner-approved drafts, apply child-directed and synthetic-media metadata, verify upload status, review performance data, and maintain security logs that do not contain secrets.</p></section><section><h2 className="text-xl font-semibold text-slate-900">Storage and sharing</h2><p>OAuth refresh tokens are encrypted at rest. Information is not sold or rented. It is shared only with Google and YouTube API Services as necessary to perform the authorized operation, and with the hosting and database infrastructure needed to operate the tool.</p></section><section><h2 className="text-xl font-semibold text-slate-900">Your controls</h2><p>The channel owner can disconnect YouTube at any time through the service. Disconnecting revokes the stored Google token and removes the encrypted connection record. Questions or requests can be sent to <a className="text-sky-700 underline" href="mailto:smallstorieshebrew@gmail.com">smallstorieshebrew@gmail.com</a>.</p></section><section><h2 className="text-xl font-semibold text-slate-900">YouTube API Services</h2><p>This service uses YouTube API Services and is subject to the <a className="text-sky-700 underline" href="https://www.youtube.com/t/terms" target="_blank" rel="noreferrer">YouTube Terms of Service</a> and Google’s <a className="text-sky-700 underline" href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Privacy Policy</a>.</p></section></LegalShell>;
}

export function TermsOfService() {
  return <LegalShell title="Terms of Service"><p>Small Stories Hebrew is an internal tool for the authorized owner of the Small Stories Hebrew YouTube channel. By connecting a channel, the owner confirms that they have authority to grant the requested Google and YouTube permissions.</p><section><h2 className="text-xl font-semibold text-slate-900">Permitted use</h2><p>The tool is used to prepare original creator-owned video drafts, apply required metadata, review quality and authorized analytics, and manage the owner’s connection. It must not be used to scrape YouTube, evade platform safeguards, impersonate users, or publish third-party content without rights.</p></section><section><h2 className="text-xl font-semibold text-slate-900">Publishing controls</h2><p>The tool defaults to private uploads. Public publishing, deletion, and visibility changes require an explicit owner decision and remain subject to YouTube policy and any applicable API restrictions.</p></section><section><h2 className="text-xl font-semibold text-slate-900">Availability and policy compliance</h2><p>The owner remains responsible for content rights, accurate child-directed settings, synthetic-media disclosures, and compliance with YouTube policies. The service may be changed or paused to preserve security or policy compliance.</p></section><section><h2 className="text-xl font-semibold text-slate-900">Contact</h2><p>For questions about these terms, contact <a className="text-sky-700 underline" href="mailto:smallstorieshebrew@gmail.com">smallstorieshebrew@gmail.com</a>.</p></section></LegalShell>;
}
